services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:DIYBQeRB9xqmYIHOCOZJpCPd6MhdvexXZ8r3ndk3nUs=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1coepbipnbc73c111gg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: vehicle_postgres_db
      - key: DB_USERNAME
        value: vehicle_postgres_db_user
      - key: DB_PASSWORD
        value: 7A0WhA2KXDMUVEqHzjYZwCD9oOTrv2fZ
